profile = "compiler"
changelog-seen = 2

[llvm]
download-ci-llvm = false
targets = "X86;AArch64;ARM"
cflags = "-fstack-protector-all"
cxxflags = "-fstack-protector-all"

[build]
target = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-gnullvm", "armv7-unknown-linux-ohos", "x86_64-unknown-linux-ohos", "aarch64-unknown-linux-ohos"]
submodules = false
compiler-docs = false
extended = true
tools = [
    "clippy",
]
docs = false
vendor = true
#verbose = 1
sanitizers = true
profiler = true

[rust]
optimize = true
codegen-units = 1
split-debuginfo = "packed"
lto = "thin-local"
backtrace = false
description = "xxxxx"
channel = "nightly"
strip = true
stack-protector = "strong"

[install]
bindir = "bin"
libdir = "lib"

[target.x86_64-unknown-linux-gnu]
cc = "clang"
cxx = "clang++"
linker = "clang"
ar = "llvm-ar"

[target.aarch64-unknown-linux-ohos]
cc = "aarch64-unknown-linux-ohos-clang"
cxx = "aarch64-unknown-linux-ohos-clang++"
linker = "aarch64-unknown-linux-ohos-clang"
ar = "llvm-ar"

[target.armv7-unknown-linux-ohos]
cc = "armv7-unknown-linux-ohos-clang"
cxx = "armv7-unknown-linux-ohos-clang++"
linker = "armv7-unknown-linux-ohos-clang"
ar = "llvm-ar"

[target.x86_64-unknown-linux-ohos]
cc = "x86_64-unknown-linux-ohos-clang"
cxx = "x86_64-unknown-linux-ohos-clang++"
linker = "x86_64-unknown-linux-ohos-clang"
ar = "llvm-ar"

[target.x86_64-pc-windows-gnullvm]
cc = "x86_64-w64-mingw32-clang"
cxx = "x86_64-w64-mingw32-clang++"
linker = "x86_64-w64-mingw32-clang"
ar = "x86_64-w64-mingw32-ar"

[dist]
compression-formats = ["gz"]