profile = "compiler"
changelog-seen = 2

[llvm]
download-ci-llvm = false
targets = "AArch64"
ninja = false
cflags = "-fstack-protector-all"
cxxflags = "-fstack-protector-all"

[build]
submodules = false
compiler-docs = false
extended = true
tools = [
    "clippy",
]
docs = false
vendor = true
#verbose = 1
#sanitizers = true
profiler = true

[rust]
optimize = true
codegen-units = 1
split-debuginfo = "packed"
lto = "thin-local"
backtrace = false
description = "xxxxx"
channel = "nightly"
strip = true
stack-protector = "all"

[install]
bindir = "bin"
libdir = "lib"

[dist]
compression-formats = ["gz"]
