[llvm]
download-ci-llvm = false  # 使用预编译LLVM加速

[build]
target = ["x86_64-unknown-linux-gnu"]  # 目标平台
extended = true  # 构建完整的工具链（包括 rustfmt、clippy 等）
tools = ["cargo", "rustfmt", "clippy", "rust-analyzer", "miri", "llvm-tools", "src", "rustdoc", "analysis", "rust-analyzer-proc-macro-srv", "wasm-component-ld", "cargo-miri"]  # 包含的工具
profiler = true

[rust]
channel = "dev"
profile-generate = "true"

[install]
prefix = "/usr/local"
